name: RSS Bot

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st day of every month at midnight (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-rss:
    name: Update repository with RSS articles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run RSS Reader script
        run: python .github/scripts/rss_bot.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git diff --quiet || git commit -m "Add new files for RSS articles"
          git push
